-- Create groups table
CREATE TABLE IF NOT EXISTS public.groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    currency text DEFAULT '₹' NOT NULL,
    emoji text,
    simplify_debts boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

-- Create group_members table
CREATE TABLE IF NOT EXISTS public.group_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES public.groups(id) ON DELETE CASCADE,
    user_email text,
    name text NOT NULL,
    phone text,
    is_pending boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- Create expenses table
CREATE TABLE IF NOT EXISTS public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES public.groups(id) ON DELETE CASCADE,
    title text NOT NULL,
    amt numeric NOT NULL,
    paid text NOT NULL, -- Name or email of payer
    date text NOT NULL,
    mode text DEFAULT 'Equally' NOT NULL,
    splitters jsonb NOT NULL, -- Array of member names/emails
    shares jsonb, -- Custom share amounts
    category text,
    currency text,
    notes text,
    attachments jsonb DEFAULT '[]'::jsonb,
    is_recurring boolean DEFAULT false,
    recurrence text DEFAULT 'none',
    next_occurrence text,
    created_at timestamp with time zone DEFAULT now()
);

-- Turn off Row Level Security (RLS) for testing and ease of use for now
ALTER TABLE public.groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
