-- Divido Production Setup and Security Configuration
-- Paste and run this script in your Supabase SQL Editor.

-- 1. Create groups table
CREATE TABLE IF NOT EXISTS public.groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    currency text DEFAULT '₹' NOT NULL,
    emoji text,
    simplify_debts boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Create group_members table
CREATE TABLE IF NOT EXISTS public.group_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES public.groups(id) ON DELETE CASCADE,
    user_email text,
    name text NOT NULL,
    phone text,
    is_pending boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Create expenses table
CREATE TABLE IF NOT EXISTS public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES public.groups(id) ON DELETE CASCADE,
    title text NOT NULL,
    amt numeric NOT NULL,
    paid text NOT NULL,
    date text NOT NULL,
    mode text DEFAULT 'Equally' NOT NULL,
    splitters jsonb NOT NULL,
    shares jsonb,
    category text,
    currency text,
    notes text,
    attachments jsonb DEFAULT '[]'::jsonb,
    is_recurring boolean DEFAULT false,
    recurrence text DEFAULT 'none',
    next_occurrence text,
    created_at timestamp with time zone DEFAULT now()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- 5. Groups policies
DROP POLICY IF EXISTS "Allow authenticated users to create groups" ON public.groups;
CREATE POLICY "Allow authenticated users to create groups" 
ON public.groups FOR INSERT 
TO authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow members to read/write their groups" ON public.groups;
CREATE POLICY "Allow members to read/write their groups" 
ON public.groups FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.group_members 
    WHERE group_members.group_id = groups.id 
    AND group_members.user_email = auth.jwt() ->> 'email'
  )
  OR
  -- Allow viewing/selecting group metadata (name, emoji) via invite link before joining
  auth.role() = 'authenticated'
);

-- 6. Group Members policies
DROP POLICY IF EXISTS "Allow authenticated users to read member list" ON public.group_members;
CREATE POLICY "Allow authenticated users to read member list"
ON public.group_members FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow members or creators to insert group members" ON public.group_members;
CREATE POLICY "Allow members or creators to insert group members"
ON public.group_members FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.group_members EXISTING
    WHERE EXISTING.group_id = group_members.group_id
    AND EXISTING.user_email = auth.jwt() ->> 'email'
  )
  OR
  NOT EXISTS (
    SELECT 1 FROM public.group_members EXISTING
    WHERE EXISTING.group_id = group_members.group_id
  )
);

DROP POLICY IF EXISTS "Allow updating member details" ON public.group_members;
CREATE POLICY "Allow updating member details"
ON public.group_members FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.group_members EXISTING
    WHERE EXISTING.group_id = group_members.group_id
    AND EXISTING.user_email = auth.jwt() ->> 'email'
  )
  OR
  user_email IS NULL
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.group_members EXISTING
    WHERE EXISTING.group_id = group_members.group_id
    AND EXISTING.user_email = auth.jwt() ->> 'email'
  )
  OR
  user_email = auth.jwt() ->> 'email'
);

DROP POLICY IF EXISTS "Allow members to delete group members" ON public.group_members;
CREATE POLICY "Allow members to delete group members"
ON public.group_members FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.group_members EXISTING
    WHERE EXISTING.group_id = group_members.group_id
    AND EXISTING.user_email = auth.jwt() ->> 'email'
  )
);

-- 7. Expenses policies
DROP POLICY IF EXISTS "Only members can access group expenses" ON public.expenses;
CREATE POLICY "Only members can access group expenses"
ON public.expenses FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_members.group_id = expenses.group_id
    AND group_members.user_email = auth.jwt() ->> 'email'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_members.group_id = expenses.group_id
    AND group_members.user_email = auth.jwt() ->> 'email'
  )
);

-- 8. Storage bucket setup for attachments
-- (Note: If this bucket configuration fails, you can also create it manually in the Supabase Storage dashboard)
INSERT INTO storage.buckets (id, name, public)
VALUES ('expense-attachments', 'expense-attachments', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Allow public read access to attachments" ON storage.objects;
CREATE POLICY "Allow public read access to attachments"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'expense-attachments');

DROP POLICY IF EXISTS "Allow authenticated users to upload attachments" ON storage.objects;
CREATE POLICY "Allow authenticated users to upload attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'expense-attachments');

DROP POLICY IF EXISTS "Allow users to update/delete their own uploads" ON storage.objects;
CREATE POLICY "Allow users to update/delete their own uploads" ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'expense-attachments' AND owner = auth.uid());

-- 9. Member avatars (shared display pictures, keyed by email)
-- Lets group members see each other's profile photo. Read is open to any
-- signed-in user (the member list is already world-readable to authenticated
-- users); writes are restricted so you can only set YOUR OWN avatar.
CREATE TABLE IF NOT EXISTS public.member_avatars (
    email text PRIMARY KEY,
    avatar_url text,
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.member_avatars ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone signed in can read avatars" ON public.member_avatars;
CREATE POLICY "Anyone signed in can read avatars"
ON public.member_avatars FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Insert own avatar" ON public.member_avatars;
CREATE POLICY "Insert own avatar"
ON public.member_avatars FOR INSERT
TO authenticated
WITH CHECK (lower(email) = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS "Update own avatar" ON public.member_avatars;
CREATE POLICY "Update own avatar"
ON public.member_avatars FOR UPDATE
TO authenticated
USING (lower(email) = lower(auth.jwt() ->> 'email'))
WITH CHECK (lower(email) = lower(auth.jwt() ->> 'email'));

-- ============================================================================
-- §10. NON-GROUP BACKUPS
-- A private per-user snapshot of the user's non-group ("STANDALONE") expenses.
-- Those expenses are stored locally on the device only; this table makes them
-- recoverable on a new device or after an accidental wipe. Only the owner can
-- read or write their own row.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.nongroup_backups (
    user_email text PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.nongroup_backups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Read own nongroup backup" ON public.nongroup_backups;
CREATE POLICY "Read own nongroup backup"
ON public.nongroup_backups FOR SELECT
TO authenticated
USING (lower(user_email) = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS "Insert own nongroup backup" ON public.nongroup_backups;
CREATE POLICY "Insert own nongroup backup"
ON public.nongroup_backups FOR INSERT
TO authenticated
WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS "Update own nongroup backup" ON public.nongroup_backups;
CREATE POLICY "Update own nongroup backup"
ON public.nongroup_backups FOR UPDATE
TO authenticated
USING (lower(user_email) = lower(auth.jwt() ->> 'email'))
WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email'));
